'use client';
import * as THREE from 'three';

export type CelestialObject = {
  id: string;
  name: string;
  type: 'star' | 'planet' | 'region';
  size: number;
  distance: number; // Semi-major axis (a) in AU for planets, used for scaling here
  color: string;
  orbitalSpeed: number; // Now represents period in Earth years
  rotationSpeed: number;
  rings?: { innerRadius: number; outerRadius: number; textureUrl: string; };
  eccentricity?: number;
  description?: string;
  diameter?: number; // in km
  mass?: string; // in 10^24 kg
  dayLength?: number; // in hours
  orbitCurve?: THREE.EllipseCurve;
  orbitalInclination?: number;
  orbitalOffset?: number; // Initial position offset, will be replaced by time-based calculation

  // Keplerian Elements for accurate orbit calculation
  semiMajorAxis: number; // a, in AU
  meanLongitude: number; // L, in degrees at J2000
  longitudeOfPerihelion: number; // ϖ, in degrees
  longitudeOfAscendingNode: number; // Ω, in degrees
};

// Simplified scaling for better visual separation
const AU_SCALE = 15; // Arbitrary unit for spacing in the 3D scene

export const solarSystemData: CelestialObject[] = [
  {
    id: 'sun',
    name: 'Sun',
    type: 'star',
    size: 6,
    distance: 0,
    color: '#FFD700',
    orbitalSpeed: 0,
    rotationSpeed: 0.05,
    description: 'The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core.',
    diameter: 1392700,
    mass: '1989000',
    semiMajorAxis: 0,
    eccentricity: 0,
    orbitalInclination: 0,
    meanLongitude: 0,
    longitudeOfPerihelion: 0,
    longitudeOfAscendingNode: 0,
  },
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'planet',
    size: 0.5,
    distance: 2.5 * AU_SCALE,
    color: '#9932CC',
    orbitalSpeed: 0.241,
    rotationSpeed: 0.1,
    description: 'Mercury is the smallest planet in the Solar System and nearest to the Sun. Its orbit takes 87.97 Earth days, the shortest of all the Sun\'s planets.',
    diameter: 4879,
    mass: '0.330',
    dayLength: 4222.6,
    semiMajorAxis: 0.387,
    eccentricity: 0.206,
    orbitalInclination: 7.00,
    meanLongitude: 252.25,
    longitudeOfPerihelion: 77.46,
    longitudeOfAscendingNode: 48.33,
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'planet',
    size: 1,
    distance: 4 * AU_SCALE,
    color: '#C19A6B',
    orbitalSpeed: 0.615,
    rotationSpeed: 0.08,
    description: 'Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the second-brightest natural object in the night sky after the Moon, Venus can cast shadows and can be, on rare occasion, visible to the naked eye in broad daylight.',
    diameter: 12104,
    mass: '4.87',
    dayLength: 2802.0,
    semiMajorAxis: 0.723,
    eccentricity: 0.007,
    orbitalInclination: 3.39,
    meanLongitude: 181.98,
    longitudeOfPerihelion: 131.53,
    longitudeOfAscendingNode: 76.68,
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'planet',
    size: 1,
    distance: 5.5 * AU_SCALE,
    color: '#1E90FF',
    orbitalSpeed: 1.000,
    rotationSpeed: 0.5,
    description: 'Our home, Earth, is the third planet from the Sun and the only astronomical object known to harbor life. About 29.2% of Earth\'s surface is land consisting of continents and islands.',
    diameter: 12742,
    mass: '5.97',
    dayLength: 24.0,
    semiMajorAxis: 1.000,
    eccentricity: 0.017,
    orbitalInclination: 0.00,
    meanLongitude: 100.46,
    longitudeOfPerihelion: 102.95,
    longitudeOfAscendingNode: -11.26,
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'planet',
    size: 0.7,
    distance: 7 * AU_SCALE,
    color: '#D2691E',
    orbitalSpeed: 1.881,
    rotationSpeed: 0.45,
    description: 'Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being only larger than Mercury. In English, Mars carries the name of the Roman god of war and is often referred to as the "Red Planet".',
    diameter: 6779,
    mass: '0.642',
    dayLength: 24.7,
    semiMajorAxis: 1.524,
    eccentricity: 0.093,
    orbitalInclination: 1.85,
    meanLongitude: -4.55,
    longitudeOfPerihelion: -23.92,
    longitudeOfAscendingNode: 49.58,
  },
  {
    id: 'itokawa',
    name: 'Itokawa',
    type: 'planet',
    size: 0.1,
    distance: 3.5 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 1.53,
    rotationSpeed: 0.2,
    description: '25143 Itokawa is a sub-kilometer near-Earth asteroid of the Apollo group and a rubble pile. It was the first asteroid to be the target of a sample-return mission, the Japanese space probe Hayabusa.',
    diameter: 0.33,
    semiMajorAxis: 1.324,
    eccentricity: 0.28,
    orbitalInclination: 1.62,
    meanLongitude: 169.3,
    longitudeOfPerihelion: 162.8,
    longitudeOfAscendingNode: 69.08,
  },
  {
    id: 'eros',
    name: 'Eros',
    type: 'planet',
    size: 0.2,
    distance: 6.2 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 1.76,
    rotationSpeed: 0.2,
    description: '433 Eros is a stony asteroid of the Amor group, and the first discovered and second-largest near-Earth object with a mean-diameter of approximately 16.8 kilometers. It was visited by the NEAR Shoemaker space probe in 1998.',
    diameter: 16.8,
    semiMajorAxis: 1.458,
    eccentricity: 0.223,
    orbitalInclination: 10.83,
    meanLongitude: 180.0,
    longitudeOfPerihelion: 178.6,
    longitudeOfAscendingNode: 304.3,
  },
  {
    id: 'bennu',
    name: 'Bennu',
    type: 'planet',
    size: 0.1,
    distance: 5.8 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 1.2,
    rotationSpeed: 0.2,
    description: '101955 Bennu is a carbonaceous asteroid in the Apollo group discovered in 1999. It is a potentially hazardous object that has a cumulative probability of 1 in 1,800 of impacting Earth between 2178 and 2290.',
    diameter: 0.49,
    semiMajorAxis: 1.126,
    eccentricity: 0.204,
    orbitalInclination: 6.03,
    meanLongitude: 135.2,
    longitudeOfPerihelion: 66.22,
    longitudeOfAscendingNode: 2.06,
  },
  {
    id: 'ryugu',
    name: 'Ryugu',
    type: 'planet',
    size: 0.1,
    distance: 6.0 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 1.3,
    rotationSpeed: 0.2,
    description: '162173 Ryugu is a near-Earth object and a potentially hazardous asteroid of the Apollo group. It is approximately 1 kilometer in diameter and is a dark C-type asteroid. Samples were returned to Earth by the Hayabusa2 spacecraft.',
    diameter: 0.9,
    semiMajorAxis: 1.19,
    eccentricity: 0.19,
    orbitalInclination: 5.88,
    meanLongitude: 355.8,
    longitudeOfPerihelion: 211.5,
    longitudeOfAscendingNode: 251.6,
  },
  {
    id: 'donaldjohanson',
    name: 'Donaldjohanson',
    type: 'planet',
    size: 0.1,
    distance: 7.5 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 3.26,
    rotationSpeed: 0.2,
    description: '52246 Donaldjohanson, provisional designation 1981 EQ5, is a stony Flora asteroid from the inner regions of the asteroid belt, approximately 4 kilometers in diameter. It is a target of the Lucy mission.',
    diameter: 4,
    semiMajorAxis: 2.19,
    eccentricity: 0.19,
    orbitalInclination: 3.96,
    meanLongitude: 145.7,
    longitudeOfPerihelion: 169.5,
    longitudeOfAscendingNode: 172.9,
  },
  {
    id: 'braille',
    name: 'Braille',
    type: 'planet',
    size: 0.1,
    distance: 8.3 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 3.58,
    rotationSpeed: 0.2,
    description: '9969 Braille is a small and highly elongated main-belt asteroid, classified as a Mars-crosser, that was discovered in 1992. It was visited by the Deep Space 1 spacecraft.',
    diameter: 1,
    semiMajorAxis: 2.34,
    eccentricity: 0.43,
    orbitalInclination: 29.0,
    meanLongitude: 240.2,
    longitudeOfPerihelion: 356.6,
    longitudeOfAscendingNode: 331.0,
  },
  {
    id: 'ceres',
    name: 'Ceres',
    type: 'planet',
    size: 0.3,
    distance: 8 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 4.6,
    rotationSpeed: 0.2,
    description: 'Ceres is the largest object in the asteroid belt between Mars and Jupiter and the only dwarf planet located in the inner Solar System. It is a C-type asteroid.',
    diameter: 940,
    semiMajorAxis: 2.77,
    eccentricity: 0.079,
    orbitalInclination: 10.59,
    meanLongitude: 147.1,
    longitudeOfPerihelion: 73.2,
    longitudeOfAscendingNode: 80.4,
  },
  {
    id: 'annefrank',
    name: 'Annefrank',
    type: 'planet',
    size: 0.1,
    distance: 8.2 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 3.28,
    rotationSpeed: 0.2,
    description: 'Annefrank is a main-belt asteroid discovered in 1942. It was named in memory of Anne Frank, the famous diarist who died in the Holocaust.',
    diameter: 4.8,
    semiMajorAxis: 2.21,
    eccentricity: 0.064,
    orbitalInclination: 4.23,
    meanLongitude: 294.6,
    longitudeOfPerihelion: 10.0,
    longitudeOfAscendingNode: 121.2,
  },
  {
    id: 'mathilde',
    name: 'Mathilde',
    type: 'planet',
    size: 0.2,
    distance: 8.5 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 4.31,
    rotationSpeed: 0.2,
    description: '253 Mathilde is a main-belt asteroid discovered in 1885. It has a relatively elliptical orbit that takes it as far as the orbit of Mars. It is a C-type asteroid.',
    diameter: 53,
    semiMajorAxis: 2.65,
    eccentricity: 0.267,
    orbitalInclination: 6.74,
    meanLongitude: 172.9,
    longitudeOfPerihelion: 181.2,
    longitudeOfAscendingNode: 179.8,
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'planet',
    size: 5,
    distance: 10 * AU_SCALE,
    color: '#E28B33',
    orbitalSpeed: 11.86,
    rotationSpeed: 0.8,
    description: 'Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined, but slightly less than one-thousandth the mass of the Sun.',
    diameter: 139820,
    mass: '1898',
    dayLength: 9.9,
    semiMajorAxis: 5.203,
    eccentricity: 0.048,
    orbitalInclination: 1.31,
    meanLongitude: 34.40,
    longitudeOfPerihelion: 14.75,
    longitudeOfAscendingNode: 100.56,
  },
  {
    id: 'eurybates',
    name: 'Eurybates',
    type: 'planet',
    size: 0.3,
    distance: 9.9 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 11.88,
    rotationSpeed: 0.2,
    description: 'Eurybates is a Greek Jupiter Trojan asteroid. It is a C-type asteroid and one of the targets of the Lucy mission. It has a small satellite, named Queta.',
    diameter: 64,
    semiMajorAxis: 5.207,
    eccentricity: 0.088,
    orbitalInclination: 8.08,
    meanLongitude: 298.6,
    longitudeOfPerihelion: 27.6,
    longitudeOfAscendingNode: 44.9,
  },
  {
    id: 'patroclus',
    name: 'Patroclus',
    type: 'planet',
    size: 0.4,
    distance: 10.1 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 11.96,
    rotationSpeed: 0.2,
    description: 'Patroclus is a large binary Jupiter Trojan asteroid. It is a P-type asteroid, which are reddish in color, and are among the darkest objects in the solar system.',
    diameter: 140,
    semiMajorAxis: 5.226,
    eccentricity: 0.138,
    orbitalInclination: 22.04,
    meanLongitude: 126.8,
    longitudeOfPerihelion: -39.1,
    longitudeOfAscendingNode: 43.8,
  },
  {
    id: 'orus',
    name: 'Orus',
    type: 'planet',
    size: 0.2,
    distance: 9.8 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 11.75,
    rotationSpeed: 0.2,
    description: 'Orus is a Jupiter Trojan from the Greek camp, approximately 51 kilometers in diameter. It is a D-type asteroid, which are very dark and reddish in appearance.',
    diameter: 51,
    semiMajorAxis: 5.17,
    eccentricity: 0.05,
    orbitalInclination: 8.47,
    meanLongitude: 247.6,
    longitudeOfPerihelion: 211.7,
    longitudeOfAscendingNode: 236.4,
  },
  {
    id: 'leucus',
    name: 'Leucus',
    type: 'planet',
    size: 0.2,
    distance: 11 * AU_SCALE,
    color: '#888888',
    orbitalSpeed: 11.69,
    rotationSpeed: 0.2,
    description: 'Leucus is another Jupiter Trojan from the Greek camp. It is a D-type asteroid, characterized by its very slow rotation, taking about 446 hours to complete one revolution.',
    diameter: 40,
    semiMajorAxis: 5.16,
    eccentricity: 0.06,
    orbitalInclination: 11.56,
    meanLongitude: 241.0,
    longitudeOfPerihelion: 169.8,
    longitudeOfAscendingNode: 161.4,
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'planet',
    size: 4,
    distance: 12.5 * AU_SCALE,
    color: '#B8860B',
    orbitalSpeed: 29.45,
    rotationSpeed: 0.75,
    rings: { innerRadius: 6, outerRadius: 10, textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/textures/saturn_ring.png' },
    description: 'Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine times that of Earth. It only has one-eighth the average density of Earth; however, with its larger volume, Saturn is over 95 times more massive.',
    diameter: 116460,
    mass: '568',
    dayLength: 10.7,
    semiMajorAxis: 9.537,
    eccentricity: 0.054,
    orbitalInclination: 2.49,
    meanLongitude: 49.94,
    longitudeOfPerihelion: 92.49,
    longitudeOfAscendingNode: 113.72,
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'planet',
    size: 3,
    distance: 15 * AU_SCALE,
    color: '#7FFFD4',
    orbitalSpeed: 84.02,
    rotationSpeed: 0.6,
    description: 'Uranus is the seventh planet from the Sun. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System. Uranus is similar in composition to Neptune, and both have bulk chemical compositions which differ from that of the larger gas giants Jupiter and Saturn.',
    diameter: 50724,
    mass: '86.8',
    dayLength: 17.2,
    semiMajorAxis: 19.19,
    eccentricity: 0.047,
    orbitalInclination: 0.77,
    meanLongitude: 313.23,
    longitudeOfPerihelion: 170.96,
    longitudeOfAscendingNode: 74.23,
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'planet',
    size: 3,
    distance: 17.5 * AU_SCALE,
    color: '#6082B6',
    orbitalSpeed: 164.8,
    rotationSpeed: 0.55,
    description: 'Neptune is the eighth and farthest-known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, slightly more massive than its near-twin Uranus.',
    diameter: 49244,
    mass: '102',
    dayLength: 16.1,
    semiMajorAxis: 30.07,
    eccentricity: 0.009,
    orbitalInclination: 1.77,
    meanLongitude: -55.12,
    longitudeOfPerihelion: 44.97,
    longitudeOfAscendingNode: 131.72,
  },
];
